# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/babysteps',
                'doc_host': 'https://Benephfer.github.io',
                'git_url': 'https://github.com/Benephfer/babysteps',
                'lib_path': 'babysteps'},
  'syms': {'babysteps.core': {'babysteps.core.foo': ('core.html#foo', 'babysteps/core.py')}}}
